import { ai, agentConfig, isLiveGeminiAvailable } from '../config/gemini';
import { PlannerOutput } from './planner.agent';
import { ResearcherOutput } from './researcher.agent';
import { CriticOutput } from './critic.agent';
import { SpecialistService } from '../services/specialist.service';
import { PrescriptionService } from '../services/prescription.service';

export async function runSynthesizerAgent(
  clinicalCase: string,
  plannerOutput: PlannerOutput,
  researcherOutput: ResearcherOutput,
  criticOutput: CriticOutput | null,
  format: 'Markdown' | 'JSON'
): Promise<string> {
  const disclaimer = `\n\n> ⚠️ **MANDATORY CLINICAL DISCLAIMER**: This report is generated by the ClinOS Autonomous AI Clinical Orchestrator for clinical decision support and triage analysis ONLY. It does not constitute formal medical diagnosis or replace professional clinical judgment. Always consult a licensed medical practitioner for patient management.`;

  // Compute specialist recommendations
  const diffConditions = researcherOutput.differentialDiagnoses.map((d) => d.condition);
  const specialistRecs = SpecialistService.recommendSpecialistsForCase(clinicalCase, diffConditions);

  // Compute evidence-based prescription regimen
  const rxPlan = PrescriptionService.generatePrescriptionPlan(clinicalCase, diffConditions);

  if (format === 'JSON') {
    const jsonOutput = {
      meta: {
        system: 'ClinOS Autonomous Multi-Agent Orchestrator',
        timestamp: new Date().toISOString(),
        disclaimer: 'Not Medical Advice - Consult a Physician',
      },
      patientCase: clinicalCase,
      triagePlanner: plannerOutput,
      clinicalResearch: researcherOutput,
      criticAudit: criticOutput || { isClinicallySafe: true, feedback: 'Critic skipped per user configuration', riskLevel: 'Low' },
      specialistReferrals: {
        primarySpecialty: specialistRecs.primarySpecialty,
        referralRationale: specialistRecs.referralRationale,
        recommendedDoctors: specialistRecs.recommendedSpecialists.map((doc) => ({
          name: doc.name,
          specialty: doc.specialty,
          hospital: doc.hospital,
          matchScore: `${doc.matchScore}%`,
          urgencyLevel: doc.urgencyLevel,
          nextSlot: doc.nextAvailableSlot,
        })),
        suggestedQuestionsForDoctor: specialistRecs.suggestedQuestionsForDoctor,
      },
      prescriptionPlan: {
        rxIdentifier: rxPlan.rxIdentifier,
        primaryTarget: rxPlan.primaryConditionTarget,
        therapeuticGoal: rxPlan.overallTherapeuticGoal,
        medications: rxPlan.prescriptions.map((rx) => ({
          genericName: rx.medication.genericName,
          brandNames: rx.medication.brandNames,
          tier: rx.tier,
          dosage: rx.dosage,
          route: rx.route,
          frequency: rx.frequency,
          duration: rx.duration,
          clinicalRationale: rx.clinicalRationale,
          criticalWarning: rx.criticalWarning,
        })),
        safetyAlerts: rxPlan.safetyAlerts,
        dietaryAndLifestyleInstructions: rxPlan.dietaryAndLifestyleInstructions,
      },
      finalCarePlan: {
        triageUrgency: researcherOutput.redFlagSymptoms.length > 1 ? 'URGENT / HIGH PRIORITY' : 'ROUTINE EVALUATION',
        recommendedNextSteps: researcherOutput.recommendedInvestigations,
      },
    };
    return JSON.stringify(jsonOutput, null, 2);
  }

  const systemInstruction = `You are the ClinOS Care Synthesizer Agent. Compile the validated findings from the Triage Planner, Clinical Researcher, Medical Critic, Specialist Referrals, and Pharmacotherapy Prescription Engine into a polished, executive-level Clinical Triage & Differential Assessment Report in clean Markdown.

Structure the report logically:
# ClinOS Autonomous Triage & Assessment Report
## Executive Case Summary
## Multi-Agent Execution Breakdown
## Prioritized Differential Diagnoses (with probability & rationale)
## Red-Flag Symptoms & Critical Risk Factors
## Recommended Diagnostic Investigations & Next Care Steps
## Recommended Specialist Consultations & Verified Doctor Referrals
## Evidence-Based Pharmacotherapy & Prescription Regimen (Rx Plan)
## Safety Critic Audit Findings`;

  const prompt = `Case Data: "${clinicalCase}"
Planner Summary: ${plannerOutput.clinicalSummary}
Researcher Data: ${JSON.stringify(researcherOutput, null, 2)}
Critic Audit: ${JSON.stringify(criticOutput, null, 2)}
Recommended Specialists: ${JSON.stringify(specialistRecs, null, 2)}
Prescription Plan: ${JSON.stringify(rxPlan, null, 2)}`;

  if (!isLiveGeminiAvailable) {
    const markdownReport = `# ClinOS Autonomous Triage & Assessment Report
**Generated by ClinOS Multi-Agent Pipeline** | *Date: ${new Date().toLocaleDateString()}*

---

### 1. Executive Case Summary
- **Chief Complaint & Context**: ${plannerOutput.clinicalSummary}
- **Assessed Urgency Level**: ${researcherOutput.redFlagSymptoms.length > 1 ? '🔴 URGENT / HIGH PRIORITY' : '🟡 MODERATE EVALUATION'}

---

### 2. Prioritized Differential Diagnoses
${researcherOutput.differentialDiagnoses
  .map(
    (d, i) =>
      `#### ${i + 1}. ${d.condition} [${d.probability} Probability]\n- **Clinical Rationale**: ${d.keyRationale}`
  )
  .join('\n\n')}

---

### 3. Red-Flag Symptoms & Clinical Safety Audit
${researcherOutput.redFlagSymptoms.map((rf) => `- 🚨 **${rf}**`).join('\n')}

**Medical Critic Guardrail Status**: 
- **Safety Rating**: ${criticOutput?.isClinicallySafe ? '✅ CLINICALLY SAFE & AUDITED' : '⚠️ REVISED UPON AUDIT'}
- **Critic Audit Notes**: ${criticOutput?.feedback || 'Validated against standard emergency triage protocols.'}

---

### 4. Actionable Next Steps & Diagnostic Investigations
${researcherOutput.recommendedInvestigations.map((inv, i) => `${i + 1}. **${inv}**`).join('\n')}

---

### 5. Recommended Specialist Consultations & Verified Doctor Referrals
- **Primary Specialty Needed**: **${specialistRecs.primarySpecialty}**
- **Clinical Referral Rationale**: ${specialistRecs.referralRationale}

**Top Verified Matching Physicians**:
${specialistRecs.recommendedSpecialists
  .map(
    (doc, idx) =>
      `${idx + 1}. **${doc.name}** (${doc.specialty} • ${doc.hospital})\n   - *Match Score*: **${doc.matchScore}% Match** | *Urgency*: **${doc.urgencyLevel}**\n   - *Next Available Slot*: ${doc.nextAvailableSlot}`
  )
  .join('\n\n')}

---

### 6. Evidence-Based Pharmacotherapy & Prescription Regimen (Rx Plan)
- **Prescription Identifier**: \`${rxPlan.rxIdentifier}\`
- **Primary Target**: ${rxPlan.primaryConditionTarget}
- **Overall Therapeutic Goal**: ${rxPlan.overallTherapeuticGoal}

**Prescribed Medication Regimen**:
${rxPlan.prescriptions
  .map(
    (rx, idx) =>
      `**Rx #${idx + 1}: ${rx.medication.genericName}** (${rx.medication.brandNames.join(', ')}) — *${rx.tier}*\n- **Dosage & Route**: ${rx.dosage} (${rx.route})\n- **Frequency & Duration**: ${rx.frequency} for ${rx.duration}\n- **Clinical Rationale**: ${rx.clinicalRationale}${
        rx.criticalWarning ? `\n- ⚠️ **Safety Precaution**: ${rx.criticalWarning}` : ''
      }`
  )
  .join('\n\n')}

${rxPlan.safetyAlerts.length > 0 ? `**Safety Alerts & Contraindication Precautions**:\n${rxPlan.safetyAlerts.map((a) => `- ${a}`).join('\n')}` : ''}

---

### 7. Multi-Agent Reasoning Trace
- **Triage Planner**: Identified key complaint and mapped execution pathway.
- **Clinical Researcher**: Evaluated differential probability vectors and symptom clusters.
- **Medical Critic**: Enforced red-flag safety guardrails.
- **Care Synthesizer**: Formatted finalized clinical report deliverable with specialist referrals and pharmacotherapy.${disclaimer}`;

    return markdownReport;
  }

  try {
    const response = await ai.models.generateContent({
      model: agentConfig.model,
      contents: prompt,
      config: {
        systemInstruction,
        temperature: agentConfig.temperature,
      },
    });

    const reportText = response.text || 'Clinical report generation completed.';
    return reportText + disclaimer;
  } catch (error) {
    console.error('Synthesizer Agent Error:', error);
    return `# ClinOS Assessment Report\n\n${researcherOutput.primaryDiagnosis}\n\n${disclaimer}`;
  }
}
