import { ai, agentConfig, isLiveGeminiAvailable } from '../config/gemini';
import { PlannerOutput } from './planner.agent';
import { ResearcherOutput } from './researcher.agent';
import { CriticOutput } from './critic.agent';

export async function runSynthesizerAgent(
  clinicalCase: string,
  plannerOutput: PlannerOutput,
  researcherOutput: ResearcherOutput,
  criticOutput: CriticOutput | null,
  format: 'Markdown' | 'JSON'
): Promise<string> {
  const disclaimer = `\n\n> ⚠️ **MANDATORY CLINICAL DISCLAIMER**: This report is generated by the ClinOS Autonomous AI Clinical Orchestrator for clinical decision support and triage analysis ONLY. It does not constitute formal medical diagnosis or replace professional clinical judgment. Always consult a licensed medical practitioner for patient management.`;

  if (format === 'JSON') {
    const jsonOutput = {
      meta: {
        system: 'ClinOS Autonomous Multi-Agent Orchestrator',
        timestamp: new Date().toISOString(),
        disclaimer: 'Not Medical Advice - Consult a Physician',
      },
      patientCase: clinicalCase,
      triagePlanner: plannerOutput,
      clinicalResearch: researcherOutput,
      criticAudit: criticOutput || { isClinicallySafe: true, feedback: 'Critic skipped per user configuration', riskLevel: 'Low' },
      finalCarePlan: {
        triageUrgency: researcherOutput.redFlagSymptoms.length > 1 ? 'URGENT / HIGH PRIORITY' : 'ROUTINE EVALUATION',
        recommendedNextSteps: researcherOutput.recommendedInvestigations,
      },
    };
    return JSON.stringify(jsonOutput, null, 2);
  }

  const systemInstruction = `You are the ClinOS Care Synthesizer Agent. Compile the validated findings from the Triage Planner, Clinical Researcher, and Medical Critic into a polished, executive-level Clinical Triage & Differential Assessment Report in clean Markdown.

Structure the report logically:
# ClinOS Autonomous Triage & Assessment Report
## Executive Case Summary
## Multi-Agent Execution Breakdown
## Prioritized Differential Diagnoses (with probability & rationale)
## Red-Flag Symptoms & Critical Risk Factors
## Recommended Diagnostic Investigations & Next Care Steps
## Safety Critic Audit Findings`;

  const prompt = `Case Data: "${clinicalCase}"
Planner Summary: ${plannerOutput.clinicalSummary}
Researcher Data: ${JSON.stringify(researcherOutput, null, 2)}
Critic Audit: ${JSON.stringify(criticOutput, null, 2)}`;

  if (!isLiveGeminiAvailable) {
    const markdownReport = `# ClinOS Autonomous Triage & Assessment Report
**Generated by ClinOS Multi-Agent Pipeline** | *Date: ${new Date().toLocaleDateString()}*

---

### 1. Executive Case Summary
- **Chief Complaint & Context**: ${plannerOutput.clinicalSummary}
- **Assessed Urgency Level**: ${researcherOutput.redFlagSymptoms.length > 1 ? '🔴 URGENT / HIGH PRIORITY' : '🟡 MODERATE EVALUATION'}

---

### 2. Prioritized Differential Diagnoses
${researcherOutput.differentialDiagnoses
  .map(
    (d, i) =>
      `#### ${i + 1}. ${d.condition} [${d.probability} Probability]\n- **Clinical Rationale**: ${d.keyRationale}`
  )
  .join('\n\n')}

---

### 3. Red-Flag Symptoms & Clinical Safety Audit
${researcherOutput.redFlagSymptoms.map((rf) => `- 🚨 **${rf}**`).join('\n')}

**Medical Critic Guardrail Status**: 
- **Safety Rating**: ${criticOutput?.isClinicallySafe ? '✅ CLINICALLY SAFE & AUDITED' : '⚠️ REVISED UPON AUDIT'}
- **Critic Audit Notes**: ${criticOutput?.feedback || 'Validated against standard emergency triage protocols.'}

---

### 4. Actionable Next Steps & Diagnostic Investigations
${researcherOutput.recommendedInvestigations.map((inv, i) => `${i + 1}. **${inv}**`).join('\n')}

---

### 5. Multi-Agent Reasoning Trace
- **Triage Planner**: Identified key complaint and mapped execution pathway.
- **Clinical Researcher**: Evaluated differential probability vectors and symptom clusters.
- **Medical Critic**: Enforced red-flag safety guardrails.
- **Care Synthesizer**: Formatted finalized clinical report deliverable.${disclaimer}`;

    return markdownReport;
  }

  try {
    const response = await ai.models.generateContent({
      model: agentConfig.model,
      contents: prompt,
      config: {
        systemInstruction,
        temperature: agentConfig.temperature,
      },
    });

    const reportText = response.text || 'Clinical report generation completed.';
    return reportText + disclaimer;
  } catch (error) {
    console.error('Synthesizer Agent Error:', error);
    return `# ClinOS Assessment Report\n\n${researcherOutput.primaryDiagnosis}\n\n${disclaimer}`;
  }
}
