import React from 'react';
import { AlertTriangle, ShieldAlert } from 'lucide-react';

interface Props {
  compact?: boolean;
}

export const MedicalDisclaimerBanner: React.FC<Props> = ({ compact = false }) => {
  if (compact) {
    return (
      <div className="bg-amber-50 border border-amber-200 rounded-lg px-3 py-2 text-amber-900 text-xs flex items-center space-x-2">
        <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0" />
        <span>
          <strong>Clinical Support System:</strong> Outputs are AI-generated clinical support materials. <em>Not Medical Advice — Consult a Physician.</em>
        </span>
      </div>
    );
  }

  return (
    <div className="w-full bg-amber-50/90 border-y border-amber-200 py-2.5 px-4 text-amber-900 text-xs shadow-sm">
      <div className="max-w-7xl mx-auto flex items-center justify-between">
        <div className="flex items-center space-x-3">
          <ShieldAlert className="w-4 h-4 text-amber-600 shrink-0" />
          <p>
            <strong className="font-semibold text-amber-800 uppercase tracking-wider text-[11px] mr-2">
              Mandatory Disclaimer:
            </strong>
            ClinOS is an autonomous decision-support system. All outputs (triage ratings, differential diagnoses, care plans) are generated by multi-agent AI models for licensed practitioner evaluation. <strong>Not Medical Advice — Always Consult a Qualified Physician.</strong>
          </p>
        </div>
        <span className="hidden md:inline-block font-mono text-[10px] bg-amber-100 px-2.5 py-0.5 rounded border border-amber-300 text-amber-800 font-semibold">
          ISO-13485 COMPLIANT BOUNDARY
        </span>
      </div>
    </div>
  );
};
